version: '3'


services:
  backend:
    container_name: backend
    restart: on-failure
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - scan-network
  frontend:
    container_name: frontend
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    networks:
      - scan-network
networks:
  scan-network:
    name: scan-network